#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh &
$HOME/.config/bspwm/picom/picom.sh &
xss-lock -- $HOME/scripts/i3_lock.sh &
$HOME/.fehbg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrandr --dpi 96x96 &
brightnessctl set 100% &
$HOME/scripts/clipster_launch.sh &
systemctl --user restart dunst &

bspc monitor -d " " " " " " " " " " " " " " " " " " " " " "

### Borders
bspc config border_width         2
bspc config focused_border_color "#f5c2e7"
bspc config normal_border_color "#313244"

### Normal Configs
bspc config pointer_motion_interval	1
bspc config window_gap		  15
bspc config focus_follows_pointer true
bspc config split_ratio            0.55
bspc config borderless_monocle     true
bspc config gapless_monocle        true

### Window Workspaces
bspc rule -a Gimp-2.10 desktop='^9' follow=on
bspc rule -a mpv state=floating
bspc rule -a discord desktop='^5'
bspc rule -a MultiMC desktop='^11'
