#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh &
$HOME/.config/bspwm/picom/picom.sh &
xss-lock -- $HOME/.config/i3/lock.sh &
$HOME/.fehbg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrandr --dpi 96x96

bspc monitor -d " " " " "ﱮ " " " " " "" " " " " " " "ﳨ " " "

### Borders
bspc config border_width         3
bspc config focused_border_color "#f5c2e7"
bspc config normal_border_color "#313244"

bspc config window_gap          20
bspc config focus_follows_pointer true
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^9' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a discord desktop='^5'
bspc rule -a MultiMC desktop='^11'
